[package]
name = "rascaline-c-api"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
edition = "2018"

[lib]
name = "rascaline"
crate-type = ["cdylib"]
bench = false

[features]
default = ["rascaline/chemfiles"]

[dependencies]
rascaline = {path = "../rascaline", version = "0.1.0", default-features = false}

[build-dependencies]
cbindgen = "0.17"
glob = "0.3"
