[package]
name = "rascaline-c-api"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
edition = "2018"

[lib]
name = "rascaline"
# when https://github.com/rust-lang/cargo/pull/8789 lands, use it here!
# until then, build all the crate-type we need
crate-type = ["cdylib", "staticlib"]
bench = false

[features]
default = ["rascaline/chemfiles"]

[dependencies]
rascaline = {path = "../rascaline", version = "0.1.0", default-features = false}
log = { version = "0.4.5", features = ["std"] }
lazy_static = "1.4.0"

[build-dependencies]
cbindgen = "0.17"
glob = "0.3"
