[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36"
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv:all]
# skip install to avoid rebuilding the world, do the install with setup.py
# instead of pip below
skip_install = True
passenv =
    RASCALINE_BUILD_TYPE
    RUSTUP_HOME
    CARGO_HOME

deps =
    discover
    numpy
    ase

commands =
    python setup.py --quiet install
    discover -p "*.py" -s python/tests

[testenv:no-ase]
skip_install = True
passenv =
    RASCALINE_BUILD_TYPE
    RUSTUP_HOME
    CARGO_HOME

deps =
    discover
    numpy

commands =
    python setup.py --quiet install
    discover -p "*.py" -s python/tests

[testenv:examples]
skip_install = True
passenv =
    RASCALINE_BUILD_TYPE
    RUSTUP_HOME
    CARGO_HOME

deps =
    discover
    numpy
    ase

commands =
    python setup.py --quiet install
    python python/examples/compute-soap.py rascaline/examples/data/water.xyz
"""
