[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36",
    "cmake",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv:all-deps]
# skip install to avoid rebuilding the world, do the install with setup.py
# instead of pip below
skip_install = True
passenv =
    RASCALINE_BUILD_TYPE
    RUSTUP_HOME
    CARGO*

deps =
    discover
    numpy
    ase
    chemfiles

commands =
    python setup.py --quiet install
    discover -p "*.py" -s python/tests

[testenv:min-deps]
skip_install = True
passenv =
    RASCALINE_BUILD_TYPE
    RUSTUP_HOME
    CARGO*

deps =
    discover
    numpy

commands =
    python setup.py --quiet install
    discover -p "*.py" -s python/tests

[testenv:examples]
skip_install = True
passenv =
    RASCALINE_BUILD_TYPE
    RUSTUP_HOME
    CARGO*

deps =
    numpy
    chemfiles

commands =
    python setup.py --quiet install
    python python/examples/compute-soap.py rascaline/examples/data/water.xyz
"""
