[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36",
    "cmake",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
line_length = 88
indent = 4
multi_line_output = "VERTICAL_HANGING_INDENT"
known_local_folder=["test_systems"]
include_trailing_comma = true
lines_after_imports = 2
known_first_party = "rascaline"
known_third_party = ["ase", "chemfiles", "docutils", "numpy"]
