[package]
name = "rascaline"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
edition = "2018"

[[bench]]
name = "spherical-harmonics"
harness = false

[[bench]]
name = "soap-radial-integral"
harness = false

[[bench]]
name = "spherical-expansion"
harness = false

[dependencies]
ndarray = {version = "0.14", features = ["approx"]}
nalgebra = "0.24"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
num-traits = "0.2"
indexmap = "1.6"
log = "0.4"
itertools = "0.10"

[dev-dependencies]
approx = "0.4"
criterion = "0.3"
glob = "0.3"
ndarray-npy = "0.7"
flate2 = "1.0.20"
