name: Test

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-18.04
            rust-version: stable
            rust-target: x86_64-unknown-linux-gnu
          - name: Linux (beta rustc)
            os: ubuntu-18.04
            rust-version: beta
            rust-target: x86_64-unknown-linux-gnu
          - name: macOS
            os: macos-10.15
            rust-version: stable
            rust-target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          target: ${{ matrix.rust-target }}

      - name: install gsl (macOS)
        if: matrix.os == 'macos-10.15'
        run: brew install gsl
      - name: install gsl (Linux)
        if: matrix.os == 'ubuntu-18.04'
        run: sudo apt install libgsl0-dev
      - name: install tests dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: run tests in debug mode
        run: cargo test --target ${{ matrix.rust-target }} -- --test-threads=2
      - name: run tests in release mode
        run: cargo test --release --target ${{ matrix.rust-target }} -- --test-threads=2
